name: Sports2014_scaling
seq_length_items: 16
filter_seen: False
column_name:
  user_col: 'user_id'
  item_col: 'item_id'
  time_col: 'timestamp'
  relevance_col:

meta_columns_to_embed: ["title", "description", "categories"]
categories_column: categories
