name: Yambda500m_listens_30d_u5_i20_scaling
seq_length_items: 100
filter_seen: False
column_name:
  user_col: uid
  item_col: item_id
  time_col: timestamp  # seconds
  relevance_col: played_ratio_pct

data_format: parquet
meta_embed_col: normalized_embed
